export const services=()=> [
  { id: '1', name: 'AC Repair & Service', category: 'House' },
  { id: '2', name: 'TV Wall Mounting', category: 'House' },
  { id: '3', name: 'Carpentry', category: 'House' },
  { id: '4', name: 'Pest Control', category: 'House' },
  { id: '5', name: 'Home Deep Cleaning', category: 'House' },
  { id: '6', name: 'Sofa Cleaning', category: 'House' },
  { id: '7', name: 'Kitchen Cleaning', category: 'House' },
  { id: '8', name: 'Water Purifier Installation', category: 'House' },
  { id: '9', name: 'Curtain Rod Installation', category: 'House' },

  { id: '10', name: 'Haircut', category: 'Beauty' },
  { id: '11', name: 'Facial', category: 'Beauty' },
  { id: '12', name: 'Manicure', category: 'Beauty' },
  { id: '13', name: 'Pedicure', category: 'Beauty' },
  { id: '14', name: 'Makeup', category: 'Beauty' },
  { id: '15', name: 'Body Spa', category: 'Beauty' },
  { id: '16', name: 'Threading', category: 'Beauty' },
  { id: '17', name: 'Waxing', category: 'Beauty' },
  { id: '18', name: 'Bridal Makeup', category: 'Beauty' },

  { id: '19', name: 'Car Repair', category: 'Mechanic' },
  { id: '20', name: 'Bike Servicing', category: 'Mechanic' },
  { id: '21', name: 'Battery Replacement', category: 'Mechanic' },
  { id: '22', name: 'Engine Diagnostics', category: 'Mechanic' },
  { id: '23', name: 'Two Wheeler Pickup/Drop', category: 'Mechanic' },
  { id: '24', name: 'Oil Change', category: 'Mechanic' },

  { id: '25', name: 'Fan Installation', category: 'Electrician' },
  { id: '26', name: 'Switch Board Repair', category: 'Electrician' },
  { id: '27', name: 'Inverter Installation', category: 'Electrician' },
  { id: '28', name: 'AC Electrical Repair', category: 'Electrician' },
  { id: '29', name: 'Light Fitting', category: 'Electrician' },
  { id: '30', name: 'Wiring Repair', category: 'Electrician' },
  { id: '31', name: 'Geyser Repair', category: 'Electrician' },

  { id: '32', name: 'Tap Repair', category: 'Plumbing' },
  { id: '33', name: 'Water Tank Cleaning', category: 'Plumbing' },
  { id: '34', name: 'Toilet Fitting', category: 'Plumbing' },
  { id: '35', name: 'Sink Unclogging', category: 'Plumbing' },
  { id: '36', name: 'Bathroom Fitting', category: 'Plumbing' },
  { id: '37', name: 'Water Pipe Leakage', category: 'Plumbing' },
  { id: '38', name: 'Shower Installation', category: 'Plumbing' },

  { id: '39', name: 'Courier Pickup', category: 'General' },
  { id: '40', name: 'Document Printing', category: 'General' },
  { id: '41', name: 'Moving & Packing', category: 'General' },
  { id: '42', name: 'Furniture Assembly', category: 'General' },
  { id: '43', name: 'Welder', category: 'General' },
  { id: '44', name: 'Heavy Lifting', category: 'General' },
  { id: '45', name: 'Labour Hire', category: 'General' },

  { id: '46', name: 'AC Repair', category: 'Cooling' },
  { id: '47', name: 'AC Installation', category: 'Cooling' },
  { id: '48', name: 'AC Gas Refill', category: 'Cooling' },
  { id: '49', name: 'AC Servicing', category: 'Cooling' },
  { id: '50', name: 'AC Uninstallation', category: 'Cooling' },
];
